# Azure DevOps YAML pipeline for Terraform AKS deployment

# Use the latest version of the pipeline runtime
pool:
  vmImage: 'ubuntu-latest'

# Define the steps in the pipeline
steps:

# Install Terraform
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.4'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'newconn' #replace with your
    scriptType: 'PowerShell'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      az account set --subscription 56edc819-264e-4a3c-be6f-1496e0b07eeb

# Initialize Terraform
- task: TerraformTaskV1@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'

# Plan the Terraform deployment
- task: TerraformTaskV1@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'

# Apply the Terraform deployment
- task: TerraformTaskV1@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'
    autoApprove: true

# Destroy the Terraform deployment
- task: TerraformTaskV1@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'
    autoApprove: true
